version: '3'
services:
  web:
    # Replace username/repo:tag with your name and image details.
    build: .
    ports:
      - '80:80'
    networks:
      - 'webnet'
  redis:
    image: redis
    networks:
      - 'webnet'
networks:
  webnet:
